<?php
$pageTitle = 'Конфигуратор';
$components = db()->query('SELECT * FROM components ORDER BY FIELD(type,"cpu","motherboard","ram","gpu","ssd","psu","case"), price')->fetchAll();
$grouped = [];
foreach ($components as $component) $grouped[$component['type']][] = $component;
require __DIR__ . '/../includes/header.php';
?><section class="hero"><div><p class="eyebrow">BUILD SMART · 01</p><h1>Соберите ПК,<br><em>который подходит.</em></h1><p class="hero-copy">Выбирайте комплектующие, а мы проверим сокет, память и запас мощности в реальном времени.</p></div><div class="hero-orb">◈<small>compatibility<br>engine</small></div></section>
<div class="layout"><section class="builder-panel"><div class="section-heading"><div><p class="eyebrow">COMPONENTS</p><h2>Комплектующие</h2></div><button class="ghost-btn" id="resetBuild">Сбросить</button></div><div class="component-grid">
<?php $labels=['cpu'=>'CPU','motherboard'=>'Материнская плата','ram'=>'Оперативная память','gpu'=>'Видеокарта','ssd'=>'SSD накопитель','psu'=>'Блок питания','case'=>'Корпус']; foreach ($labels as $type=>$label): ?><label class="component-card"><span class="card-top"><span><?= e($label) ?></span><b><?= strtoupper($type) ?></b></span><select data-type="<?= $type ?>" class="component-select"><option value="">Выберите <?= e(mb_strtolower($label)) ?></option><?php foreach (($grouped[$type] ?? []) as $item): ?><option value="<?= (int)$item['id'] ?>" data-price="<?= $item['price'] ?>"><?= e($item['name']) ?> · <?= number_format((float)$item['price'],0,',',' ') ?> ₽</option><?php endforeach; ?></select><span class="select-arrow">↓</span></label><?php endforeach; ?></div><div id="compatibility" class="compatibility-panel empty"><span class="status-dot"></span><div><strong>Выберите комплектующие</strong><p>Здесь появится результат проверки совместимости.</p></div></div><div class="builder-actions"><button class="primary-btn" id="saveBuild">Сохранить сборку <span>↗</span></button><button class="secondary-btn" id="exportPdf">Экспорт PDF <span>↗</span></button></div></section><aside class="summary-panel"><div class="summary-head"><p class="eyebrow">BUILD SUMMARY</p><span id="summaryStatus">DRAFT</span></div><h2>Ваша сборка</h2><div id="summaryList" class="summary-list"><p class="muted">Компоненты появятся здесь</p></div><div class="total"><span>Итого</span><strong id="totalPrice">0 ₽</strong></div><div class="tip"><span>✦</span><p>Подсказка: начните с процессора — он определит сокет и тип памяти.</p></div></aside></div>
<script>window.PC_COMPONENTS = <?= json_encode($components, JSON_UNESCAPED_UNICODE) ?>; window.PC_PLAN = <?= json_encode($user['plan'] ?? 'guest') ?>;</script><?php require __DIR__ . '/../includes/footer.php';
